package com.example.project_part_3;

/**
 * Dummy R class used only for Javadoc generation.
 * The real R class is generated by the Android Gradle Plugin at build time.
 */
public final class R {
    private R() {}

    public static final class id {}
    public static final class layout {}
    public static final class drawable {}
    public static final class string {}
    public static final class menu {}
    public static final class mipmap {}
    public static final class color {}
    public static final class dimen {}
    public static final class style {}
}
